server:
  port: 0
  servlet:
    context-path: /user

spring:
  application:
    name: user
  datasource:    url: jdbc:mysql://localhost:3306/myth?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 
  jpa:    hibernate:      ddl-auto: none    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8083/eureka