server:
  port: 0
  servlet:
    context-path: /product

spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/liquid?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8020/auth/realms/liquid-dev/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8083/eureka