server:
  port: 0
  servlet:
    context-path: /notification

spring:
  application:
    name: notification
  mail:    host: smtp.gmail.com
    port: 587
    username: guduktolunay@gmail.com
    password: T.g5356032012
    properties:      mail: 
        smtp:
          auth: true
          starttls: 
            enable: true

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8083/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
    list:
      user: localhost:8080/user
    