server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:8083/eureka
  instance:
    instance-id: ${spring.application.name}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
      - id: report
        uri: lb://report
        predicates:
        - Path=/report/**
      - id: notification
        uri: lb://notification
        predicates:
        - Path=/notification/**
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8020/auth/realms/liquid