server:
  port: 0
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        provider:
          liquid-provider:
            issuer-uri: http://localhost:8020/auth/realms/liquid-dev
        registration:
          keycloak-spring-gateway-client:
            provider: liquid-provider
            scope: openid
            client-id: liquid-client
            client-secret: x6duQXvCooKAErTPMs8re9kDPeDo7gp9
            authorization-grant-type: password

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8083/eureka


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
    list:
      user: localhost:8080/user


