server:
  port: 0
  servlet:
    context-path: /report

spring:
  application:
    name: report
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8020/auth/realms/liquid-dev/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8083/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
    list:
      user: localhost:8080/user
    